# Generated by Django 4.0.6 on 2022-07-12 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dish', models.CharField(max_length=100)),
                ('review', models.CharField(choices=[('N', 'Never again'), ('W', 'Would go back')], default='N', max_length=1)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.blog')),
            ],
        ),
    ]
